version: '3.5'

services:
  myapp_nginx:
    build: ./nginx
    container_name: myapp_nginx
    ports:
      - "8282:80"
    volumes:
      - ../app:/var/www/
      - ../logs:/var/log/nginx
      - ./nginx/conf/myapp.conf:/etc/nginx/conf.d/myapp.conf
    depends_on:
      - myapp_php

  myapp_php:
    build: ./php
    container_name: myapp_php
    links:
      - myapp_mongo
      - myapp_mysql
    volumes:
      - ../app:/var/www/
    working_dir: /var/www

  myapp_mongo:
    image: mongo:3.4.10
    container_name: myapp_mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"

  myapp_mysql:
    container_name: myapp_mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mm
    ports:
      - "3306:3306"
    expose:
      - "3306"

  myapp_phpmyadmin:
    container_name: myapp_phpmyadmin
    image: phpmyadmin/phpmyadmin:4.7
    links:
      - myapp_mysql
    environment:
      PMA_HOST: myapp_mysql
      PMA_PORT: 3306
    ports:
      - '8383:80'